### ISSUE TITLE
Upgrade meilisearch-php to version 0.21

### ISSUE THREAD

**Issue by flemming-petersen** [elvenstar/statamic-meilisearch#2]
It is required to have meilisearch-php 0.21 installed to work with Meilisearch 0.25.

**Comment by tao** [comment]
I've started updated the versioning system to match that of MeiliSearch as they're going through a lot of breaking changes while the software continues to mature. To work with v0.24 you can now install the latest release:

```json
"elvenstar/statamic-meilisearch": "^0.24"
```

This week I'm testing out compatibility with v0.25, which you can try out early by installing the v25 branch:

```json
"elvenstar/statamic-meilisearch": "v25.x-dev"
```

I'm testing it out with my own project but you can also let me know if you run into any bugs too.

**Comment by flemming-petersen** [comment]
That's fantastic. Version 0.24 works fine. I will test the v25-dev branch. Thanks a lot.
