### ISSUE TITLE
Question regarding filters

### ISSUE THREAD

**Issue by MartinVandersteen** [elvenstar/statamic-meilisearch#4]
Hello and sorry for the disturbance ! Feel free to close the issue without explanation if this is not the place to ask questions.

I have trouble making a filter work using the plugin, here is what I'm doing : 
`Statamic\Facades\Search::index('my_index')->searchUsingApi(Request::input('q'), ['filter' => ['category = a-taxonomy-term']])`

Here is what a record in meilisearch looks like : 
```json
{
  "id":"be604825-d780-481d-b623-e13b30c82c2d",
  "title":"test title",
  "reponse":"<p>test<br></p>",
  "tags":["test1","test2","test3"],
  "category":["a-taxonomy-term","another-one"],
  "collection":"my-collection"
}
```

I can't seem to make my filter work, I'm trying to get only results that are linked to a specify taxonomy term. Am I doing something wrong ?

Thanks a lot for the great plugin !

**Comment by tao** [comment]
The first issue is that the driver doesn't take a second paramater, but I'll update it to allow filters:

```
public function searchUsingApi($query)
=> public function searchUsingApi($query, $filters)
```

So you're calling `searchUsingApi(Request::input('q'), ['filter' => ['category = a-taxonomy-term']])` and the filter variable was being lost. 

Next you'll need to make sure that `category` is set up as a filter/facet on MeiliSearch, you can do that on the global settings in `config/search.php`

For example:

```
// articles
'my_index' => [
    'driver' => 'meilisearch',
    'searchables' => ['collection:my_collection'],
    'fields' => ['id', 'title', 'category', 'content', 'tags', 'collection', 'response'],
    'settings' => [
      'filterableAttributes' => ['category'],
    ],
],
```

However I haven't done any testing on adding an array field like that `["a-taxonomy-term","another-one"]` to MeiliSearch.

For anything complex I would recommend using the MeiliSearch PHP library directly.

**Comment by MartinVandersteen** [comment]
Thanks a lot for your help ! I will have a look at it and turn to the PHP Library if I can't make it work :) Have a great day!
